[package]
name = "wadah-oci"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
oci-distribution.workspace = true
tokio.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

